version: '3'
services: # what is your container do you have
  node-app: # first container
    build:  #build this container file docker 
      context: .
      target: development
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=DEV
    command: npm run start 