version: '3'
services: # what is your container do you have
  node-app: # first container
    container_name: simple-node
    build: . #build this container file docker 
    volumes:
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=PRODUCTION